# add your desired knowledge graph components here

case study:
  represented_as: node
  input_label: :CaseStudy
  is_a: named thing
  properties:
    name: str
    description: str

organ:
  represented_as: node
  input_label: :Organ
  is_a: gross anatomical structure
  properties:
    name: str

web page:
  represented_as: node
  is_a: named thing
  input_label: :WebPage
  synonym: web page
  properties:
    name: str

AOP:
  represented_as: node
  input_label: :AOP
  is_a: named thing
  properties:
    name: str # From AOPName
    id: str # From AOPID
    creator: str # From AOPcreator
    description: str # From AOPDescription
    source: str

key event:
  represented_as: node
  input_label: :KeyEvent # This defines how the node will be labeled in your graph
  is_a: named thing
  properties:
    name: str # Represents the name of the key event
    KEID: str # Represents the ID of the key event
    description: str

chemical:
  represented_as: node
  input_label: :Chemical
  synonym_for: small molecule
  properties:
    name: str
    CAS: str
    SMILES: str
    InChIKey: str
    chemical group: str

bioassay:
  is_a: named thing
  represented_as: node
  input_label: :Bioassay
  properties:
    name: str
    measured: str

model system:
  is_a: organismal entity
  represented_as: node
  input_label: :Model_system
  properties:
    name: str
    cell type: str
    description: str

computational model:
  is_a: information content entity
  represented_as: node
  input_label: :Computational_model
  properties:
    name: str
    type: str
    language: str
    input: str
    output: str

measurable endpoint:
  represented_as: node
  is_a: phenomenon
  input_label: :Measurable_endpoint
  properties:
    name: str
    description: str
    type: str

experimental condition:
  is_a: study variable
  represented_as: node
  input_label: :Experimental_condition
  properties:
    exposure_duration: str
    exposure_concentration: str
    condition_name: str
    description: str

case study related organ:
  is_a: association
  represented_as: edge
  source: case study
  target: organ
  input_label: case_study_related_organ

AOP includes mie: # Links to MIE node
  is_a: association
  represented_as: edge
  source: AOP
  target: key event
  input_label: AOP_includes_mie

AOP includes ao: # Links to AO node
  is_a: association
  represented_as: edge
  source: AOP
  target: key event
  input_label: AOP_includes_ao

AOP includes key event: # Links to AOPKE (Key Event) node
  is_a: association
  represented_as: edge
  source: AOP
  target: key event # Assumes AOPKE points to a KeyEvent node
  input_label: AOP_includes_key_event

AOP relevant stressor: # Links to AOPStressor (stressor node)
  is_a: association
  represented_as: edge
  source: AOP
  target: stressor # Assumes AOPStressor points to a Stressor node
  input_label: AOP_relevant_stressor

chemical measured with bioassay:
  is_a: association
  represented_as: edge
  source: chemical
  target: bioassay
  input_label: chemical_measured_with_bioassay

bioassay executed on model system:
  is_a: association
  represented_as: edge
  source: bioassay
  target: model system
  input_label: bioassay_executed_on_model_system

case study relevant chemical:
  is_a: association
  represented_as: edge
  source: case study
  target: chemical
  input_label: case_study_relevant_chemical

case study relevant model system:
  is_a: association
  represented_as: edge
  source: case study
  target: model system
  input_label: case_study_relevant_model_system

case study relevant computational model:
  is_a: association
  represented_as: edge
  source: case study
  target: computational model
  input_label: case_study_relevant_computational_model

case study relevant aop:
  is_a: association
  represented_as: edge
  source: case study
  target: AOP
  input_label: case_study_related_aop

case study relevant key event:
  is_a: association
  represented_as: edge
  source: case study
  target: key event
  input_label: case_study_related_ke

chemical measured in model system:
  is_a: association
  represented_as: edge
  source: chemical
  target: model system
  input_label: chemical_measured_in_model_system

chemical relevant to computational model:
  is_a: association
  represented_as: edge
  source: chemical
  target: computational model
  input_label: chemical_relevant_to_computational_model

bioassay related organ:
  is_a: association
  represented_as: edge
  source: bioassay
  target: organ
  input_label: bioassay_related_organ

model system relevant to organ:
  is_a: association
  represented_as: edge
  source: model system
  target: organ
  input_label: model_system_relevant_to_organ

computational model relevant to organ:
  is_a: association
  represented_as: edge
  source: computational model
  target: organ
  input_label: computational_model_relevant_to_organ

case study relevant endpoint:
  is_a: association
  represented_as: edge
  source: case study
  target: measurable endpoint
  input_label: case_study_relevant_endpoint

bioassay used with experimental condition:
  is_a: association
  represented_as: edge
  source: bioassay
  target: experimental_condition
  input_label: bioassay_used_with_experimental_condition

chemical to web page association:
  is_a: association
  represented_as: edge
  source: chemical
  target: web page
  input_label: chemical_webpage

key event relationship:
  is_a: association
  represented_as: edge
  source: key event
  target: key event
  input_label: key_event_relationship
